### ISSUE TITLE
For mange "partiprogram", vanskelig å navigere, samt mulige konflikter

### ISSUE THREAD

**Issue by MarlinMr** [piratpartiet/pir-politisk-program#19]
Det finnes alt for mange "partiprogram" som er aktive repos. De har ikke sammenkoblet git-historikk og ser ut til å bli lagt til av enkeltpersoner ganske tilfeldig etter et landsmøte eller lignende. 

Nettsiden linker til https://github.com/piratpartiet/pir-politisk-program, men hvis man googler, får man gjerne opp https://www.piratpartiet.no/kjerneprogrammet/, som ikke er lik https://github.com/piratpartiet/pir-politisk-program. På https://github.com/piratpartiet/pir-kjerneprogram står det at det ikke er i bruk lengre. https://github.com/piratpartiet/pir-valgprogram er et tredje program som bare ligger der.

Det er veldig vanskelig å vite hva som gjelder. Feks dukket det opp [en tråd på reddit](https://www.reddit.com/r/norge/comments/p6ue0s/piratpartiet_skriver_i_partiprogrammet_sitt_at_de/), hvor det lenkes til forskjellige program. Ingen vet hva som faktisk gjelder. 

Hvorfor er ikke programmene bare et repo som blir endret kontinuerlig?

I https://github.com/piratpartiet/pir-politisk-program/blob/master/README.md står det at programmet er vedtatt i 2019.

I https://github.com/piratpartiet/pir-politisk-program/blob/master/Partiprogram.md står det "Sist oppdatert 30. mai 2021."

I git-historikken står det at siste endring ble gjort 23. juni. Historikken er også bare en haug med "Update Partiprogram.md" fra @theDurkan. Hvem er det? Har denne personen mulighet til å bare endre partiprogrammet ved et tastetrykk?

I https://github.com/piratpartiet/pir-kjerneprogram/issues er det en haug med forslag som er åpne. 

Kort sagt, det er veldig forvirrende å vite hva Piratpartiet mener om noe som helst når nettsiden linker til et repo hvor ting er så "rotete". Håper dere har mulighet til å rydde opp i dette eller i det minste svare på spørsmålene.

**Comment by Targeir-Attestog** [comment]
TheDurken er Filip Durkan Aasheim, som er leiar i programkomiteen i
Piratpartiet.

Mvh.
Targeir Attestog,
tidlegare leiar i programkomiteen

ons. 18. aug. 2021, 22:52 skrev MarlinMr ***@***.***>:

**Comment by Targeir-Attestog** [comment]
Politisk program og piratkodeksen er det som tel no. Resten er historie.
Har lagt inn kommentar i readme-fil om det. Kan gjere det tydelegare.


Viss ein går frå Piratpartiet.no, er det bare politisk program og
piratkodeksen som blir linka til derifrå.

Mvh.
Targeir Attestog,
tidlegare leiar i programkomiteen til Piratpartiet

ons. 18. aug. 2021, 23:48 skrev Targeir Attestog ***@***.***>:

**Comment by theDurkan** [comment]
Det er kun en kodeks og et program som gjelder som Targeir påpeker. Det er
et poeng at https://github.com/piratpartiet/pir-politisk-program og
https://www.piratpartiet.no/kjerneprogrammet/ skal være like, ettersom
kjerneprogrammet på piratpartiet.no skal hente teksten fra Github-repoet
automatisk. Nå linkes det istedenfor direkte til Github, som det kan
diskuteres om er hensiktsmessig. At gammelt
https://www.piratpartiet.no/kjerneprogrammet/ (gammelt i den forstand at
det kun mangler de siste vedtakene fra sist landsmøte 2021, ellers er det
gjeldende politikk der) er det som dukker opp når man Googler er
problematisk ja, så fint du sa ifra. Vi får da se på hvorfor den siden ikke
har oppdatert seg med det nyeste jeg har lagt inn i Github.

Det har nok oppstått litt ulike partiprogrammer på Github da programmet har
vært igjennom større revideringer tidligere, hvor man har vurdert at det er
enklere å skrive ett nytt enn å flikke på eksisterende. Partiet har av
fokuset på åpenhet heller valgt å la det ligge enn å slette. I programmet
det linkes til på Redditen, står det bla.; *Dette er kjerneprogram for
Piratpartiet Norge slik det var frem til vedtak om omstrukturering på
landsmøtet april 2019. Kjerneprogrammet er ikke lenger en del av
Piratpartiets program. Det vises til Politisk program som vedtatt på samme
landsmøte. *- Men det er muligens ikke tydelig nok siden folk alikevel
klarer å finne den frem og lenke til den.

At dagens gjeldene repo har uklar endringshistorikk ligger nok på min
kappe, da det er jeg som har oppdatert programmet for å samsvare med
vedtakene fra sist landsmøte. Jeg er ingen racer på Github, så den kunne
sikkert blitt oppdatert på en bedre måte. Endringene er forankret i
landsmøtevedtak. Det er uansett ikke tenkt at folk nødvendigvis skal inn og
grave i repoet og endringshistorikken for å finne informasjon, alt som er
relevant politikk skal jo stå på hovedsiden.

Endret dato oppført i partiprogrammet er dato for landsmøte, altså dagen
selve vedtakene om ny politikk ble vedtatt. Dato i Github 23 juni er dato
for når selve endringen ble lagt inn i repoet. Vedtatt dato og endret dato
er derfor to forskjellige ting.

Men vi tar en dialog på det internt, og ser om vi kan arkivere eller rydde
bort unødvendige og ikke-gjeldende programmer for at det ikke er
uoversiktlig.

// Filip


ons. 18. aug. 2021 kl. 23:49 skrev Targeir Attestog <
***@***.***>:

**Comment by MarlinMr** [comment]
Der er mulig å sette et repo til "arkivert" hvor det fremdeles er tilgjengelig til å kunne leses, men ikke endres. Da markerer også github det tydelig som arkivert. Issues i andre repoer burde jo også lukkes i henhold til hva som ble vedtatt på landsmøte.

Når man først har valgt git og github til versionskontroll og publisering, vil jeg personlig påstå at det er fordelaktig å ha kun 1 repo som oppdateres. Der lager man en branch man kaller `forslag-landsmøte-20xx`. Før et landsmøte kan det opprettes merge requests til den branchen. Under landsmøte kan de da fortløpende bli meget eller rejected. Så merger man landsmøte branchen inn i master når det er vedtatt.

At nettsiden linker til github er litt problematisk for de som ikke har brukt github før ja. Derfor bør heller det settes opp automatisk generering av en egen nettside fra repoet, slik det er vanlig å publisere dokumentasjon til forskjellige git prosjekter i dag. Sett sammen med om det bare var et repo, vil da alltid oppdatert partiprogram vært lett tilgjengelig.

Jeg vil anta at det er en andel av velger eller medlem av pp som har god erfaring med git, så dette burde være relativt greit å få orden på med litt støtte.

**Comment by Targeir-Attestog** [comment]
Tusen takk for tips! Vi få ordna dette så fort vi kan.

Vi har hatt problem med at når vi har brukt plugin på ei side på nettstaden
vår til å gjengi innhald frå GitHub, så fungerer ikkje linkane i
innhaldslista der. Eg kan sjå i helga kva eg kan få til. Har vore opptatt
med andre ting i det siste.

Mvh.
Targeir

tor. 19. aug. 2021, 09:38 skrev MarlinMr ***@***.***>:

**Comment by Targeir-Attestog** [comment]
@MarlinMr @theDurkan Har arkivert alle utdaterte program på GitHub.
På piratpartiet.no er det no ikkje lenger linking til GitHub, men i staden ei eiga side der med manuell kopi av GitHub-teksten. 
Det er ikkje verre enn at ein må ta manuell kopi av alt og overskrive innhald på Wordpress-sida når vi gjer endring i GitHub-program. Formatering blir faktisk ganske bra på automatisk vis med Wordpress-editoren.

Måtte ta vekk innhaldsliste på Wordpress-sida, for linkane der fungerer ikkje, og eg har ikkje tid til å lage nytt innhaldslistesystem som fungerer på Wordpress-sida.

https://www.piratpartiet.no/politisk-program/
